# Robot Profile 将 Core、Hardware、Description、Controllers 和 MoveIt 组装为可启动实例
# 本文件只保存 SerialArm-Core 仓库内置 Profile；下游机器人可在自己的 package 中维护独立 robot_profiles.yaml
# package + relative path 由 SerialArm resource resolver 解析
# package 一般应位于 robot_supports/robots/<robot_name>/description 下，作为 robot_description 的资源包
# ROS 2 环境下，同一 resource package 可以同时作为 ament package 使用

profiles:
  dm_arm_gray:  # 全局唯一 Profile 名，建议采用 <robot_name>_<variant>
    core:
      package: dm_arm_description       # Core YAML 所在 resource package
      config: config/core/gray.yaml     # Core 配置相对路径
    hardware:
      plugin: serial_arm_hardware_damiao  # HardwareLoader 加载的 Backend
      config_package: dm_arm_description  # Hardware YAML 所在 resource package
      config: config/hardware.yaml        # Hardware 配置相对路径
    description:
      package: dm_arm_description                                     # Robot Description 所在 resource package
      urdf: model/gray/urdf/dm_arm_no_gripper.urdf                    # display 使用的 URDF
      ros2_control_xacro: model/gray/urdf/dm_arm.ros2_control.xacro   # ros2_control Xacro
    controllers:
      package: dm_arm_description          # Controllers 配置所在 resource package
      config: config/ros2_controllers.yaml # controller_manager 配置
    moveit:
      package: dm_arm_no_gripper  # 当前 Profile 使用的 MoveIt 配置包

  dm_arm_white:  # 全局唯一 Profile 名，建议采用 <robot_name>_<variant>
    core:
      package: dm_arm_description       # Core YAML 所在 resource package
      config: config/core/white.yaml    # Core 配置相对路径
    hardware:
      plugin: serial_arm_hardware_damiao  # HardwareLoader 加载的 Backend
      config_package: dm_arm_description  # Hardware YAML 所在 resource package
      config: config/hardware.yaml        # Hardware 配置相对路径
    description:
      package: dm_arm_description                                     # Robot Description 所在 resource package
      urdf: model/white/urdf/dm_arm.urdf                              # display 使用的 URDF
      ros2_control_xacro: model/white/urdf/dm_arm.ros2_control.xacro  # ros2_control Xacro
    controllers:
      package: dm_arm_description          # Controllers 配置所在 resource package
      config: config/ros2_controllers.yaml # controller_manager 配置
    moveit:
      package: dm_arm_with_gripper  # 当前 Profile 使用的 MoveIt 配置包
