#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_TYPE="${BUILD_TYPE:-Release}"
CONAN_DIR="${CONAN_DIR:-${ROOT_DIR}/build/conan}"
CORE_BUILD_DIR="${CORE_BUILD_DIR:-${ROOT_DIR}/build/serial_arm_core}"
INSTALL_PREFIX="${INSTALL_PREFIX:-${ROOT_DIR}/install/standalone}"
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || printf '1')}"
ROBOT=""

usage() {
    cat <<'USAGE'
Usage: ./tools/bootstrap_standalone.sh [--robot dm_arm]

Without --robot, build, test and install the standalone SerialArm Core only.
With --robot dm_arm, also install the Damiao USB2CAN protocol, Damiao hardware
backend, robot profiles and DM-Arm resources required by dm_arm_gray/white.

Environment overrides:
  BUILD_TYPE       CMake build type (default: Release)
  CONAN_DIR        Conan generator directory
  CORE_BUILD_DIR   Core build directory
  INSTALL_PREFIX   Standalone install prefix
  JOBS             Parallel build jobs
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --robot)
            if [[ $# -lt 2 ]]; then
                printf 'error: --robot requires a value\n' >&2
                exit 2
            fi
            ROBOT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'error: unknown argument: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -n "${ROBOT}" && "${ROBOT}" != "dm_arm" ]]; then
    printf 'error: unsupported robot: %s (supported: dm_arm)\n' "${ROBOT}" >&2
    exit 2
fi

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        printf 'error: required command not found: %s\n' "$1" >&2
        return 1
    fi
}

configure_build_install() {
    local source_dir="$1"
    local build_dir="$2"
    shift 2

    cmake \
        -S "${source_dir}" \
        -B "${build_dir}" \
        -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
        -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
        -DCMAKE_PREFIX_PATH="${INSTALL_PREFIX}" \
        "$@"
    cmake --build "${build_dir}" --parallel "${JOBS}"
    cmake --install "${build_dir}" --prefix "${INSTALL_PREFIX}"
}

require_command conan
require_command cmake
require_command ctest

case "$(conan --version)" in
    "Conan version 2."*) ;;
    *)
        printf 'error: Conan 2 is required, got: %s\n' "$(conan --version)" >&2
        exit 2
        ;;
esac

if ! conan profile path default >/dev/null 2>&1; then
    conan profile detect
fi

conan install "${ROOT_DIR}" \
    --output-folder="${CONAN_DIR}" \
    --build=missing \
    -s build_type="${BUILD_TYPE}"

TOOLCHAIN_FILE="${CONAN_DIR}/conan_toolchain.cmake"
if [[ ! -f "${TOOLCHAIN_FILE}" ]]; then
    printf 'error: Conan did not generate %s\n' "${TOOLCHAIN_FILE}" >&2
    exit 3
fi

cmake \
    -S "${ROOT_DIR}/src/serial_arm/core" \
    -B "${CORE_BUILD_DIR}" \
    -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
    -DSERIAL_ARM_BUILD_PYTHON=OFF \
    -DSERIAL_ARM_BUILD_TERMINAL=ON \
    -DBUILD_TESTING=ON

cmake --build "${CORE_BUILD_DIR}" --parallel "${JOBS}"

RUNENV_FILE="${CONAN_DIR}/conanrun.sh"
if [[ ! -f "${RUNENV_FILE}" ]]; then
    printf 'error: Conan did not generate runtime environment: %s\n' "${RUNENV_FILE}" >&2
    exit 4
fi

# shellcheck disable=SC1091
source "${RUNENV_FILE}"

ctest --test-dir "${CORE_BUILD_DIR}" --output-on-failure
cmake --install "${CORE_BUILD_DIR}" --prefix "${INSTALL_PREFIX}"

if [[ "${ROBOT}" == "dm_arm" ]]; then
    configure_build_install \
        "${ROOT_DIR}/src/robot_supports/protocol/damiao_usb2can" \
        "${ROOT_DIR}/build/serial_arm_protocol_damiao_usb2can" \
        -DBUILD_TESTING=OFF

    configure_build_install \
        "${ROOT_DIR}/src/robot_supports/hardware/damiao" \
        "${ROOT_DIR}/build/serial_arm_hardware_damiao" \
        -DBUILD_TESTING=OFF

    configure_build_install \
        "${ROOT_DIR}/src/robot_supports/profiles" \
        "${ROOT_DIR}/build/serial_arm_robot_profiles"

    configure_build_install \
        "${ROOT_DIR}/src/robot_supports/robots/dm_arm/description" \
        "${ROOT_DIR}/build/dm_arm_description"
fi

mkdir -p "${INSTALL_PREFIX}"
SETUP_FILE="${INSTALL_PREFIX}/setup.bash"
cat > "${SETUP_FILE}" <<EOF_SETUP
#!/usr/bin/env bash
# Generated by tools/bootstrap_standalone.sh
# shellcheck disable=SC1091
source "${RUNENV_FILE}"
export SERIAL_ARM_RESOURCE_PATH="${INSTALL_PREFIX}"
export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:\${LD_LIBRARY_PATH:-}"
EOF_SETUP
chmod +x "${SETUP_FILE}"

printf '\nStandalone Core is ready\n'
printf '  build:   %s\n' "${CORE_BUILD_DIR}"
printf '  install: %s\n' "${INSTALL_PREFIX}"
if [[ "${ROBOT}" == "dm_arm" ]]; then
    printf '  robot:   dm_arm (protocol + hardware + profiles + description)\n'
fi
printf '\nBefore running installed binaries in a new shell:\n'
printf '  source %q\n' "${SETUP_FILE}"
if [[ "${ROBOT}" == "dm_arm" ]]; then
    printf '  serial_arm_terminal --robot-profile dm_arm_gray\n'
fi
